# Generated by Django 2.2.5 on 2020-11-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartCustomer',
        ),
    ]
